# Generated by Django 3.2.7 on 2021-09-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutyou',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bloodgroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Accounts.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastdonate',
            field=models.DateField(blank=True),
        ),
    ]
