# Generated by Django 3.2.7 on 2021-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0002_auto_20210929_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('blood doner', 'Blood Doner'), ('money doner', 'MOney Doner')], max_length=20),
        ),
    ]
