# Generated by Django 3.2.7 on 2021-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0003_alter_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastdonate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
