# Generated by Django 3.2.7 on 2021-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0005_alter_profile_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar7.png', upload_to='Profile'),
        ),
    ]
