# Generated by Django 3.2.7 on 2021-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar7.png', upload_to='Profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('blood doner', 'Blood Doner'), ('money doner', 'Money Doner')], max_length=20),
        ),
    ]
