# Generated by Django 3.2.7 on 2021-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blood', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('president_image', models.ImageField(default='avatar7.png', upload_to='Branch/')),
                ('president_message', models.TextField(max_length=1000)),
                ('vicepresident_image', models.ImageField(default='avatar7.png', upload_to='Branch/')),
                ('vicepresident_message', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
