# Generated by Django 3.2.7 on 2021-10-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blood', '0005_bloodrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='BranchSlider/')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Blood.branch')),
            ],
        ),
    ]
